### ISSUE TITLE
endless debug message loops while creating vm

### ISSUE THREAD

**Issue by siftuser** [hatching/vmcloak#179]
facing issue similar to https://github.com/hatching/vmcloak/issues/84

`vmcloak init -d --verbose --win7x64 win7 --cpus 2 --ramsize 2048`

Upon executing above command, same vmcloak DEBUG message repeats endlessly until manually aborted (CTRL+c)

```
INFO:vmcloak:Starting the Virtual Machine u'win7' to install Windows.
DEBUG:vmcloak.vm:Running command: ['/usr/bin/VBoxManage', 'startvm', u'win7', '--type', 'headless']
. . .
<snip>
. . .
DEBUG:vmcloak.vm:Running command: ['/usr/bin/VBoxManage', 'startvm', u'win7', '--type', 'headless']
```

**Comment by samwakel** [comment]
Did you give it a Windows ISO? I can't see it's mount location specified in your command

-------- Original message --------

**Comment by siftuser** [comment]
Thank you @samwakel 

The ISO is mounted at `/mnt/win7`

Per `https://hatching.io/blog/cuckoo-sandbox-setup/`, `VMCloak will try /mnt/win7 (and /mnt/win7x64) by default.`

**Comment by siftuser** [comment]
Thank you @samwakel 

FYI - I was able to install base Windows. I think it was vbox issue .. had to reinstall that.
