### ISSUE TITLE
I tried to create vmcloak but it takes so long time is it normal

### ISSUE THREAD

**Issue by Faitouri** [hatching/vmcloak#193]
(cuckoo-test) cuckoo@cuckoo:~/Desktop$ vmcloak init --verbose --win7x64 win7x64base --cpus 2 --ramsize 2048
/home/cuckoo/.virtualenvs/cuckoo-test/local/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
INFO:vmcloak.abstract:Got file 'python-2.7.6.msi' from 'https://www.python.org/ftp/python/2.7.6/python-2.7.6.msi', with matching checksum.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO:vmcloak:Starting the Virtual Machine u'win7x64base' to install Windows.

**Comment by jaykeerti** [comment]
@Faitouri Did it ever end?

**Comment by RadamireZ** [comment]
In my case, snapshot is taking a lot of time. I never saw the end, but it seem works looking at the dimension of the created folder in vms.

**Comment by ezavalar** [comment]
You should wait until it finish, you can open virtualbox to see the progress, or you can use the parameters -v -d to see it on console, for example:  vmcloak init --verbose --win7x64 win7x64base --cpus 2 --ramsize 2048 -v -d
**It takes a long time!**

**Comment by Faitouri** [comment]
Thank you for every one the problem was related to the specification of my laptop. when I worked on anther higher PC the environment was setup and work
