### ISSUE TITLE
vmcloak is taking forever

### ISSUE THREAD

**Issue by Toqahassib** [hatching/vmcloak#208]
the following command has been running for more than 3 hrs

<img width="468" alt="image" src="https://user-images.githubusercontent.com/70861082/211204810-01888c8b-d2a4-480f-b80a-a0c422449861.png">

is this normal?

**Comment by Cryss76** [comment]
nope, it isn't; can you use the --vm-visible to see if the vm started and what is happening in it?

**Comment by Toqahassib** [comment]
I used another command on an earlier ubuntu version and it worked, thank you
